package odaprice;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Krlitos
 */
public class Autorizacion extends javax.swing.JFrame {

    EnviadorDeEmail enviar=new EnviadorDeEmail();
    
    public Autorizacion() {
        initComponents();
        this.setLocationRelativeTo(null);
        //Ponemos un icono a la aplicación
        setIconImage (new ImageIcon(getClass().getResource("/imagenes/iso_oda2-01.png")).getImage());
        //para ponerle el nombre de la aplicación
        this.setTitle("");
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textClave = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnEnnviarCorreo = new javax.swing.JButton();
        labelAlerta = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 275));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Clave de autorización:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 160, 14);
        getContentPane().add(textClave);
        textClave.setBounds(20, 30, 107, 20);

        btnEntrar.setText("Entrar");
        btnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEntrarMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEntrarMousePressed(evt);
            }
        });
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar);
        btnEntrar.setBounds(140, 30, 80, 23);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Si no recuerda la contraseña,se puede \nenviar la misma, a la siguiente dirección \nde correo \"sistemas@parbras.com.ar\".");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 100, 368, 80);

        btnEnnviarCorreo.setText("Enviar Correo");
        btnEnnviarCorreo.setEnabled(false);
        btnEnnviarCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnnviarCorreoActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnnviarCorreo);
        btnEnnviarCorreo.setBounds(250, 190, 137, 23);

        labelAlerta.setBackground(new java.awt.Color(255, 255, 51));
        labelAlerta.setForeground(new java.awt.Color(255, 255, 51));
        getContentPane().add(labelAlerta);
        labelAlerta.setBounds(20, 60, 180, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bg_consulta_precios_ODA-01.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-200, 0, 610, 250);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMousePressed
        
    }//GEN-LAST:event_btnEntrarMousePressed

    private void btnEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseClicked
        
    }//GEN-LAST:event_btnEntrarMouseClicked

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        if(textClave.getText().equals("")){
            labelAlerta.setText("Debe ingresar una clave !");
        }else{
            if(textClave.getText().equals("sistemas789")){
                ConfigCorreo config=new ConfigCorreo();
                this.setVisible(false);
                config.setVisible(true);
            }else{
                labelAlerta.setText("CLAVE INCORRECTA!");
            }
        }
        
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseEntered
       
    }//GEN-LAST:event_btnEntrarMouseEntered

    private void btnEnnviarCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnnviarCorreoActionPerformed
        enviar.setMensaje("La clave del consultador de precios de ODA es 'sistemas789'.");
        enviar.setCorreo("carar14187@hotmail.com");
        enviar.sendEmail();
        JOptionPane.showMessageDialog(null, "Correo Enviado...","",JOptionPane.INFORMATION_MESSAGE);
        this.setVisible(false);
    }//GEN-LAST:event_btnEnnviarCorreoActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Autorizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Autorizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Autorizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Autorizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Autorizacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnnviarCorreo;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelAlerta;
    private javax.swing.JPasswordField textClave;
    // End of variables declaration//GEN-END:variables
}
