/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package odaprice;

import static javax.management.Query.gt;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Krlitos
 */
public class ConfigCorreo extends javax.swing.JFrame {

    EnviadorDeEmail enviar=new EnviadorDeEmail();
    
    public ConfigCorreo() {
        initComponents();
        this.setLocationRelativeTo(null);
        //Ponemos un icono a la aplicación
        setIconImage (new ImageIcon(getClass().getResource("/imagenes/iso_oda2-01.png")).getImage());
        //para ponerle el nombre de la aplicación
        this.setTitle("Configuraciones");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textCorreo = new javax.swing.JTextField();
        textHost = new javax.swing.JTextField();
        textPuerto = new javax.swing.JTextField();
        textDestinatario = new javax.swing.JTextField();
        textPassword = new javax.swing.JPasswordField();
        btnConfirmar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboTransporte = new javax.swing.JComboBox();
        fondoConfigCorreo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 350));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Correo:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 30, 60, 14);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 70, 110, 14);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Puerto:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 150, 90, 14);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Host:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 110, 60, 14);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Destinatario:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(210, 220, 120, 14);
        getContentPane().add(textCorreo);
        textCorreo.setBounds(290, 30, 230, 20);

        textHost.setText("mail.parbras.com.ar");
        getContentPane().add(textHost);
        textHost.setBounds(290, 110, 230, 20);

        textPuerto.setText("9025");
        getContentPane().add(textPuerto);
        textPuerto.setBounds(290, 150, 50, 20);
        getContentPane().add(textDestinatario);
        textDestinatario.setBounds(290, 220, 231, 20);
        getContentPane().add(textPassword);
        textPassword.setBounds(290, 70, 230, 20);

        btnConfirmar.setText("Guardar Cambios");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmar);
        btnConfirmar.setBounds(380, 260, 140, 23);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Transporte:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(360, 150, 80, 20);

        jComboTransporte.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SMTP", "POP3" }));
        getContentPane().add(jComboTransporte);
        jComboTransporte.setBounds(440, 150, 80, 20);

        fondoConfigCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bg_consulta_precios_ODA-01.jpg"))); // NOI18N
        getContentPane().add(fondoConfigCorreo);
        fondoConfigCorreo.setBounds(-20, -260, 580, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        
        //validacion de Correo del usuario
        if(textCorreo.getText()!=""){enviar.setUser(textCorreo.getText());}
        //validacion de password del usuario
        char[] arrayP=textPassword.getPassword();
        String pass=new String(arrayP);
        if(pass!=""){enviar.setPassword(pass);}
       
        //validacion del Host
        if(textHost.getText()!=""){enviar.setHost(textHost.getText());}
        //validacion del puerto
        if(textPuerto.getText()!=""){enviar.setPuerto(Integer.parseInt(textPuerto.getText()));}
        enviar.setTransporte((String) jComboTransporte.getSelectedItem());
        //validacion del correo destinatario
        if(textDestinatario.getText()!=""){enviar.setCorreo(textDestinatario.getText());}
        enviar.setMensaje("Test de Configuración para envío de correos. ");
        enviar.sendEmail();
        JOptionPane.showMessageDialog(null, "Validando sus datos....");
    }//GEN-LAST:event_btnConfirmarActionPerformed

    public JComboBox getjComboBox1() {
        return jComboTransporte;
    }

    public void setjComboBox1(JComboBox jComboBox1) {
        this.jComboTransporte = jComboBox1;
    }

    public JTextField getTextCorreo() {
        return textCorreo;
    }

    public void setTextCorreo(JTextField textCorreo) {
        this.textCorreo = textCorreo;
    }

    public JTextField getTextDestinatario() {
        return textDestinatario;
    }

    public void setTextDestinatario(JTextField textDestinatario) {
        this.textDestinatario = textDestinatario;
    }

    public JTextField getTextHost() {
        return textHost;
    }

    public void setTextHost(JTextField textHost) {
        this.textHost = textHost;
    }

    public JPasswordField getTextPassword() {
        return textPassword;
    }

    public void setTextPassword(JPasswordField textPassword) {
        this.textPassword = textPassword;
    }

    public JTextField getTextPuerto() {
        return textPuerto;
    }

    public void setTextPuerto(JTextField textPuerto) {
        this.textPuerto = textPuerto;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfigCorreo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel fondoConfigCorreo;
    private javax.swing.JComboBox jComboTransporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField textCorreo;
    private javax.swing.JTextField textDestinatario;
    private javax.swing.JTextField textHost;
    private javax.swing.JPasswordField textPassword;
    private javax.swing.JTextField textPuerto;
    // End of variables declaration//GEN-END:variables
}
